---
title: "codes"
author: "Tim"
date: "2022-12-12"
output: html_document
---
```{r}
#package
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```
# step 1 -- get all wanted variables from different data set
```{r}
#sort the data
### get data1
rawdata <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/IGF1data.csv')
data <- rawdata %>%
  select(ID, APOE4_status, family_history_AD, Sex, Age_Baseline, age1of3groups, SmokingY08, AlcoholY08, BMI_Y08andY12andY14_mean, rsfMRI_Component1, rsfMRI_Component5, rsfMRI_Component7, rsfMRI_Component9, rsfMRI_Component13, rsfMRI_Component14, rsfMRI_Component20)
#data1 includes fMRI, sex, age, AOPE4, smoking, alcohol, family history, and BMI
rm(rawdata)
write.csv(data, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\data1.csv", row.names=FALSE)
rm(list = ls())
```

```{r}
### get data2 -- AOPE4 & Tomm40_650
rawdata <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/UKB_Jan_27_2020.csv')
data <- rawdata %>%
  select(EID, APOE_all, T40_Gcar)
#data1 includes sex, age, AOPE4, TOMM40, family history
rm(rawdata)
#set APOE state, syntax is from https://www.statology.org/replace-values-in-data-frame-r/
data['APOE_all'][data['APOE_all']=='e2/e4'|data['APOE_all']=='e4/e3'|data['APOE_all']=='e4/e4'] <- '1'
data['APOE_all'][data['APOE_all']=='e2/e3'|data['APOE_all']=='e3/e3'|data['APOE_all']=='e2/e2'] <- '0'
data['APOE_all'][data['APOE_all']=='NA/NA'] <- 'NA'
colnames(data)[1]<-"eid"
write.csv(data, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\data2.csv", row.names=FALSE)
rm(list = ls())
```

```{unix}
#get data3
#cheese and milk data is extracted by Unix because the original data is too large
## this version of cheese and milk type is from the rawdata
$ awk -F',' -v OFS=, '{print $1,$50,$51,$52,$53,$54,$55,$56,$57}' ukb42102_2020May26_Genomic_Medical.csv > rawdata.csv
#rawdata is renamed data3 which includes "CheeseBaselineL"-1408-0.0, "Cheese1repeatL"1408-1.0, "CheeseImagingVisitL"1408-2.0, "MilkTypebaselineL"1418-0.0, "MilkType1repeatL"1418-1.0, "MilkTypeImageVisitL"1418-2.0
```


```{r}
### get data4 -- cheese intake, Red wine intake, milk type from Brandon's data
rawdata <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/UKBiobank_Masterfile_rename.csv')
data <- rawdata %>%
  select(eid, CheeseBaseline, Cheese1repeat, CheeseImagingVisit, MilkTypebaseline, MilkType1repeat, MilkTypeImageVisit,RedWine_Baselineb,RedWine_1repeatb,Redwine_imageb)
rm(rawdata)
write.csv(data, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\data4.csv", row.names=FALSE)
rm(list = ls())
# https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=1408 cheese dictionary
# cheese intake: "0 : Never 1 : Less than once a week 2 : Once a week 3 : 2-4 times a week 4 : 5-6 times a week 5 : Once or more daily  -1 : Do not know  -3 : Prefer not to answer"
# milk type: 1 : Full cream 2 : Semi-skimmed 3 : Skimmed 4 : Soya 5 : Other type of milk 6 : Never/rarely have milk -1 : Do not know -3 : Prefer not to answer
```

```{unix}
### get data5 -- get milk intake
### this raw data is too large, so I have to use unix
# step 1: get the header line
$ egrep "eid" ukb42166_2020JUN01.csv > header_ukb42166.csv
# check wanted vairables to know which columes they are
$ awk -F',' -v OFS=, '{print $1,$3624,$3625,$3626,$3627,$3628,$3629,$3630,$3631,$3632,$3633,$3754,$3755,$3756,$3757,$3758}' ukb42166_2020JUN01.csv > data5.csv
# data5 includes 100520-0.0	100520-1.0	100520-2.0	100520-3.0	100520-4.0	100530-0.0	100530-1.0	100530-2.0	100530-3.0	100530-4.0	100920-0.0	100920-1.0	100920-2.0	100920-3.0	100920-4.0, naming MilkIntakeBaseline	MilkIntake1	MilkIntake2	MilkIntake3	MilkIntake4	FMilkIntakeBaseline	FMilkIntake1	FMilkIntake2	FMilkIntake3	FMilkIntake4	MilkTypeBaseline	MilkType1	MilkType2	MilkType3	MilkType4
# data5_redwine is for 24h red wine data. It is made by using the same method of data5
```
#step 2 merge 5 data
```{r}
###data1 and data2 have different ID names. THey are changed to eid manually
#merge five data together
#merge the least sample, in which only same participants are kept
dataa <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/data1.csv')
datab <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/data2.csv')
datac<-merge(dataa,datab,by="eid")
rm(dataa)
rm(datab)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/data3.csv')
datab<-merge(dataa,datac,by="eid")
rm(dataa)
rm(datac)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/data4.csv')
datac<-merge(dataa,datab,by="eid")
rm(dataa)
rm(datab)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/data5.csv')
datab<-merge(dataa,datac,by="eid")
rm(dataa)
rm(datac)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/data5_redwine.csv')
datac<-merge(dataa,datab,by="eid")
rm(dataa)
rm(datab)
colnames(datac)[1]<-"EID"
write.csv(datac, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#merge five data together
#merge the most sample, in which all participants are kept
#!this function is not used because it's meaningless to keep all participants.
datac<-merge(dataa,datab,by="eid", all.x =TRUE, all.y =TRUE)
```

```{r}
#add townsend data (189)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_mean.csv')
datab<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/data6_townsend.csv')
datac<-merge(dataa,datab,by="eid")
rm(dataa)
rm(datab)
colnames(datac)[1]<-"EID"
write.csv(datac, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_all.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#add IC10
rawdata <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/IGF1data.csv')
dataa <- rawdata %>%
  select(eid, rsfMRI_Component10)
datab<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_all.csv')
datac<-merge(dataa,datab,by="eid")
rm(dataa)
rm(datab)
colnames(datac)[1]<-"EID"
write.csv(datac, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{unix}
#add cheese24 hour data
### get data7 -- get cheese 24 data
### this raw data is too large, so I have to use unix
# step 1: get the header line
$ egrep "eid" ukb42166_2020JUN01.csv > header_ukb42166.csv
# check wanted vairables to know which columes they are (4159-4218)
$ awk -F',' -v OFS=, '{print $1,$4159,$4160,$4161,$4162,$4163,$4164,$4165,$4166,$4167,$4168,$4169,$4170,$4171,$4172,$4173,$4174,$4175,$4176,$4177,$4178,$4179,$4180,$4181,$4182,$4183,$4184,$4185,$4186,$4187,$4188,$4189,$4190,$4191,$4192,$4193,$4194,$4195,$4196,$4197,$4198,$4199,$4200,$4201,$4202,$4203,$4204,$4205,$4206,$4207,$4208,$4209,$4210,$4211,$4212,$4213,$4214,$4215,$4216,$4217,$4218}' ukb42166_2020JUN01.csv > data7_cheese24_all.csv
# data7 includes 102800-102910
```

```{r}
#merge data7 with others
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data.csv')
datab<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/data7_cheese24_all.csv')
datac<-merge(dataa,datab,by="eid")
rm(dataa)
rm(datab)
colnames(datac)[1]<-"EID"
write.csv(datac, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#delete meaningless values in cheese24 data; 555 is half; 200 is NA, 0 is NA
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data.csv')
dataa$Cheese24_810Baseline[dataa$Cheese24_810Baseline == '555'] <- '0.5'
dataa$Cheese24_810Baseline[dataa$Cheese24_810Baseline == '200'] <- '0'
dataa$Cheese24_810Baseline[dataa$Cheese24_810Baseline == '300'] <- '3'
dataa$Cheese24_810Baseline[dataa$Cheese24_810Baseline == '0'] <- ''
dataa$Cheese24_810_1[dataa$Cheese24_810_1 == '555'] <- '0.5'
dataa$Cheese24_810_1[dataa$Cheese24_810_1 == '200'] <- '0'
dataa$Cheese24_810_1[dataa$Cheese24_810_1 == '300'] <- '3'
dataa$Cheese24_810_1[dataa$Cheese24_810_1 == '0'] <- ''
dataa$Cheese24_820Baseline[dataa$Cheese24_820Baseline == '555'] <- '0.5'
dataa$Cheese24_820Baseline[dataa$Cheese24_820Baseline == '200'] <- '0'
dataa$Cheese24_820Baseline[dataa$Cheese24_820Baseline == '300'] <- '3'
dataa$Cheese24_820_1[dataa$Cheese24_820_1 == '555'] <- '0.5'
dataa$Cheese24_820_1[dataa$Cheese24_820_1 == '200'] <- '0'
dataa$Cheese24_820_1[dataa$Cheese24_820_1 == '300'] <- '3'
dataa$Cheese24_820Baseline[dataa$Cheese24_820Baseline == '0'] <- ''
dataa$Cheese24_820_1[dataa$Cheese24_820_1 == '0'] <- ''
dataa$Cheese24_830Baseline[dataa$Cheese24_830Baseline == '555'] <- '0.5'
dataa$Cheese24_830Baseline[dataa$Cheese24_830Baseline == '200'] <- '0'
dataa$Cheese24_830Baseline[dataa$Cheese24_830Baseline == '300'] <- '3'
dataa$Cheese24_830_1[dataa$Cheese24_830_1 == '555'] <- '0.5'
dataa$Cheese24_830_1[dataa$Cheese24_830_1 == '200'] <- '0'
dataa$Cheese24_830_1[dataa$Cheese24_830_1 == '300'] <- '3'
dataa$Cheese24_830Baseline[dataa$Cheese24_830Baseline == '0'] <- ''
dataa$Cheese24_830_1[dataa$Cheese24_830_1 == '0'] <- ''
dataa$Cheese24_840Baseline[dataa$Cheese24_840Baseline == '555'] <- '0.5'
dataa$Cheese24_840Baseline[dataa$Cheese24_840Baseline == '200'] <- '0'
dataa$Cheese24_840Baseline[dataa$Cheese24_840Baseline == '300'] <- '3'
dataa$Cheese24_840_1[dataa$Cheese24_840_1 == '555'] <- '0.5'
dataa$Cheese24_840_1[dataa$Cheese24_840_1 == '200'] <- '0'
dataa$Cheese24_840_1[dataa$Cheese24_840_1 == '300'] <- '3'
dataa$Cheese24_850Baseline[dataa$Cheese24_850Baseline == '555'] <- '0.5'
dataa$Cheese24_850Baseline[dataa$Cheese24_850Baseline == '200'] <- '0'
dataa$Cheese24_850Baseline[dataa$Cheese24_850Baseline == '300'] <- '3'
dataa$Cheese24_850_1[dataa$Cheese24_850_1 == '555'] <- '0.5'
dataa$Cheese24_850_1[dataa$Cheese24_850_1 == '200'] <- '0'
dataa$Cheese24_850_1[dataa$Cheese24_850_1 == '300'] <- '3'
dataa$Cheese24_860Baseline[dataa$Cheese24_860Baseline == '555'] <- '0.5'
dataa$Cheese24_860Baseline[dataa$Cheese24_860Baseline == '200'] <- '0'
dataa$Cheese24_860Baseline[dataa$Cheese24_860Baseline == '300'] <- '3'
dataa$Cheese24_860_1[dataa$Cheese24_860_1 == '555'] <- '0.5'
dataa$Cheese24_860_1[dataa$Cheese24_860_1 == '200'] <- '0'
dataa$Cheese24_860_1[dataa$Cheese24_860_1 == '300'] <- '3'
dataa$Cheese24_870Baseline[dataa$Cheese24_870Baseline == '555'] <- '0.5'
dataa$Cheese24_870Baseline[dataa$Cheese24_870Baseline == '200'] <- '0'
dataa$Cheese24_870Baseline[dataa$Cheese24_870Baseline == '300'] <- '3'
dataa$Cheese24_870_1[dataa$Cheese24_870_1 == '555'] <- '0.5'
dataa$Cheese24_870_1[dataa$Cheese24_870_1 == '200'] <- '0'
dataa$Cheese24_870_1[dataa$Cheese24_870_1 == '300'] <- '3'
dataa$Cheese24_880Baseline[dataa$Cheese24_880Baseline == '555'] <- '0.5'
dataa$Cheese24_880Baseline[dataa$Cheese24_880Baseline == '200'] <- '0'
dataa$Cheese24_880Baseline[dataa$Cheese24_880Baseline == '300'] <- '3'
dataa$Cheese24_880_1[dataa$Cheese24_880_1 == '555'] <- '0.5'
dataa$Cheese24_880_1[dataa$Cheese24_880_1 == '200'] <- '0'
dataa$Cheese24_880_1[dataa$Cheese24_880_1 == '300'] <- '3'
dataa$Cheese24_890Baseline[dataa$Cheese24_890Baseline == '555'] <- '0.5'
dataa$Cheese24_890Baseline[dataa$Cheese24_890Baseline == '200'] <- '0'
dataa$Cheese24_890Baseline[dataa$Cheese24_890Baseline == '300'] <- '3'
dataa$Cheese24_890_1[dataa$Cheese24_890_1 == '555'] <- '0.5'
dataa$Cheese24_890_1[dataa$Cheese24_890_1 == '200'] <- '0'
dataa$Cheese24_890_1[dataa$Cheese24_890_1 == '300'] <- '3'
dataa$Cheese24_900Baseline[dataa$Cheese24_900Baseline == '555'] <- '0.5'
dataa$Cheese24_900Baseline[dataa$Cheese24_900Baseline == '200'] <- '0'
dataa$Cheese24_900Baseline[dataa$Cheese24_900Baseline == '300'] <- '3'
dataa$Cheese24_900_1[dataa$Cheese24_900_1 == '555'] <- '0.5'
dataa$Cheese24_900_1[dataa$Cheese24_900_1 == '200'] <- '0'
dataa$Cheese24_900_1[dataa$Cheese24_900_1 == '300'] <- '3'
dataa$Cheese24_910Baseline[dataa$Cheese24_910Baseline == '555'] <- '0.5'
dataa$Cheese24_910Baseline[dataa$Cheese24_910Baseline == '200'] <- '0'
dataa$Cheese24_910Baseline[dataa$Cheese24_910Baseline == '300'] <- '3'
dataa$Cheese24_910_1[dataa$Cheese24_910_1 == '555'] <- '0.5'
dataa$Cheese24_910_1[dataa$Cheese24_910_1 == '200'] <- '0'
dataa$Cheese24_910_1[dataa$Cheese24_910_1 == '300'] <- '3'
dataa$Cheese24_840Baseline[dataa$Cheese24_840Baseline == '0'] <- ''
dataa$Cheese24_840_1[dataa$Cheese24_840_1 == '0'] <- ''
dataa$Cheese24_850Baseline[dataa$Cheese24_850Baseline == '0'] <- ''
dataa$Cheese24_850_1[dataa$Cheese24_850_1 == '0'] <- ''
dataa$Cheese24_860Baseline[dataa$Cheese24_860Baseline == '0'] <- ''
dataa$Cheese24_860_1[dataa$Cheese24_860_1 == '0'] <- ''
dataa$Cheese24_870Baseline[dataa$Cheese24_870Baseline == '0'] <- ''
dataa$Cheese24_870_1[dataa$Cheese24_870_1 == '0'] <- ''
dataa$Cheese24_880Baseline[dataa$Cheese24_880Baseline == '0'] <- ''
dataa$Cheese24_880_1[dataa$Cheese24_880_1 == '0'] <- ''
dataa$Cheese24_890Baseline[dataa$Cheese24_890Baseline == '0'] <- ''
dataa$Cheese24_890_1[dataa$Cheese24_890_1 == '0'] <- ''
dataa$Cheese24_900Baseline[dataa$Cheese24_900Baseline == '0'] <- ''
dataa$Cheese24_900_1[dataa$Cheese24_900_1 == '0'] <- ''
dataa$Cheese24_910Baseline[dataa$Cheese24_910Baseline == '0'] <- ''
dataa$Cheese24_910_1[dataa$Cheese24_910_1 == '0'] <- ''
dataa$Cheese24_810_2[dataa$Cheese24_810_2 == '555'] <- '0.5'
dataa$Cheese24_810_2[dataa$Cheese24_810_2 == '200'] <- '0'
dataa$Cheese24_810_2[dataa$Cheese24_810_2 == '300'] <- '3'
dataa$Cheese24_810_2[dataa$Cheese24_810_2 == '0'] <- ''
dataa$Cheese24_820_2[dataa$Cheese24_820_2 == '555'] <- '0.5'
dataa$Cheese24_820_2[dataa$Cheese24_820_2 == '200'] <- '0'
dataa$Cheese24_820_2[dataa$Cheese24_820_2 == '300'] <- '3'
dataa$Cheese24_820_2[dataa$Cheese24_820_2 == '0'] <- ''
dataa$Cheese24_830_2[dataa$Cheese24_830_2 == '555'] <- '0.5'
dataa$Cheese24_830_2[dataa$Cheese24_830_2 == '200'] <- '0'
dataa$Cheese24_830_2[dataa$Cheese24_830_2 == '300'] <- '3'
dataa$Cheese24_830_2[dataa$Cheese24_830_2 == '0'] <- ''
dataa$Cheese24_840_2[dataa$Cheese24_840_2 == '555'] <- '0.5'
dataa$Cheese24_840_2[dataa$Cheese24_840_2 == '200'] <- '0'
dataa$Cheese24_840_2[dataa$Cheese24_840_2 == '300'] <- '3'
dataa$Cheese24_850_2[dataa$Cheese24_850_2 == '555'] <- '0.5'
dataa$Cheese24_850_2[dataa$Cheese24_850_2 == '200'] <- '0'
dataa$Cheese24_850_2[dataa$Cheese24_850_2 == '300'] <- '3'
dataa$Cheese24_860_2[dataa$Cheese24_860_2 == '555'] <- '0.5'
dataa$Cheese24_860_2[dataa$Cheese24_860_2 == '200'] <- '0'
dataa$Cheese24_860_2[dataa$Cheese24_860_2 == '300'] <- '3'
dataa$Cheese24_870_2[dataa$Cheese24_870_2 == '555'] <- '0.5'
dataa$Cheese24_870_2[dataa$Cheese24_870_2 == '200'] <- '0'
dataa$Cheese24_870_2[dataa$Cheese24_870_2 == '300'] <- '3'
dataa$Cheese24_880_2[dataa$Cheese24_880_2 == '555'] <- '0.5'
dataa$Cheese24_880_2[dataa$Cheese24_880_2 == '200'] <- '0'
dataa$Cheese24_880_2[dataa$Cheese24_880_2 == '300'] <- '3'
dataa$Cheese24_890_2[dataa$Cheese24_890_2 == '555'] <- '0.5'
dataa$Cheese24_890_2[dataa$Cheese24_890_2 == '200'] <- '0'
dataa$Cheese24_890_2[dataa$Cheese24_890_2 == '300'] <- '3'
dataa$Cheese24_900_2[dataa$Cheese24_900_2 == '555'] <- '0.5'
dataa$Cheese24_900_2[dataa$Cheese24_900_2 == '200'] <- '0'
dataa$Cheese24_900_2[dataa$Cheese24_900_2 == '300'] <- '3'
dataa$Cheese24_910_2[dataa$Cheese24_910_2 == '555'] <- '0.5'
dataa$Cheese24_910_2[dataa$Cheese24_910_2 == '200'] <- '0'
dataa$Cheese24_910_2[dataa$Cheese24_910_2 == '300'] <- '3'
dataa$Cheese24_840_2[dataa$Cheese24_840_2 == '0'] <- ''
dataa$Cheese24_850_2[dataa$Cheese24_850_2 == '0'] <- ''
dataa$Cheese24_860_2[dataa$Cheese24_860_2 == '0'] <- ''
dataa$Cheese24_870_2[dataa$Cheese24_870_2 == '0'] <- ''
dataa$Cheese24_880_2[dataa$Cheese24_880_2 == '0'] <- ''
dataa$Cheese24_890_2[dataa$Cheese24_890_2 == '0'] <- ''
dataa$Cheese24_900_2[dataa$Cheese24_900_2 == '0'] <- ''
dataa$Cheese24_910_2[dataa$Cheese24_910_2 == '0'] <- ''
dataa$Cheese24_810_3[dataa$Cheese24_810_3 == '555'] <- '0.5'
dataa$Cheese24_810_3[dataa$Cheese24_810_3 == '200'] <- '0'
dataa$Cheese24_810_3[dataa$Cheese24_810_3 == '300'] <- '3'
dataa$Cheese24_810_3[dataa$Cheese24_810_3 == '0'] <- ''
dataa$Cheese24_820_3[dataa$Cheese24_820_3 == '555'] <- '0.5'
dataa$Cheese24_820_3[dataa$Cheese24_820_3 == '200'] <- '0'
dataa$Cheese24_820_3[dataa$Cheese24_820_3 == '300'] <- '3'
dataa$Cheese24_820_3[dataa$Cheese24_820_3 == '0'] <- ''
dataa$Cheese24_830_3[dataa$Cheese24_830_3 == '555'] <- '0.5'
dataa$Cheese24_830_3[dataa$Cheese24_830_3 == '200'] <- '0'
dataa$Cheese24_830_3[dataa$Cheese24_830_3 == '300'] <- '3'
dataa$Cheese24_830_3[dataa$Cheese24_830_3 == '0'] <- ''
dataa$Cheese24_840_3[dataa$Cheese24_840_3 == '555'] <- '0.5'
dataa$Cheese24_840_3[dataa$Cheese24_840_3 == '200'] <- '0'
dataa$Cheese24_840_3[dataa$Cheese24_840_3 == '300'] <- '3'
dataa$Cheese24_850_3[dataa$Cheese24_850_3 == '555'] <- '0.5'
dataa$Cheese24_850_3[dataa$Cheese24_850_3 == '200'] <- '0'
dataa$Cheese24_850_3[dataa$Cheese24_850_3 == '300'] <- '3'
dataa$Cheese24_860_3[dataa$Cheese24_860_3 == '555'] <- '0.5'
dataa$Cheese24_860_3[dataa$Cheese24_860_3 == '200'] <- '0'
dataa$Cheese24_860_3[dataa$Cheese24_860_3 == '300'] <- '3'
dataa$Cheese24_870_3[dataa$Cheese24_870_3 == '555'] <- '0.5'
dataa$Cheese24_870_3[dataa$Cheese24_870_3 == '200'] <- '0'
dataa$Cheese24_870_3[dataa$Cheese24_870_3 == '300'] <- '3'
dataa$Cheese24_880_3[dataa$Cheese24_880_3 == '555'] <- '0.5'
dataa$Cheese24_880_3[dataa$Cheese24_880_3 == '200'] <- '0'
dataa$Cheese24_880_3[dataa$Cheese24_880_3 == '300'] <- '3'
dataa$Cheese24_890_3[dataa$Cheese24_890_3 == '555'] <- '0.5'
dataa$Cheese24_890_3[dataa$Cheese24_890_3 == '200'] <- '0'
dataa$Cheese24_890_3[dataa$Cheese24_890_3 == '300'] <- '3'
dataa$Cheese24_900_3[dataa$Cheese24_900_3 == '555'] <- '0.5'
dataa$Cheese24_900_3[dataa$Cheese24_900_3 == '200'] <- '0'
dataa$Cheese24_900_3[dataa$Cheese24_900_3 == '300'] <- '3'
dataa$Cheese24_910_3[dataa$Cheese24_910_3 == '555'] <- '0.5'
dataa$Cheese24_910_3[dataa$Cheese24_910_3 == '200'] <- '0'
dataa$Cheese24_910_3[dataa$Cheese24_910_3 == '300'] <- '3'
dataa$Cheese24_840_3[dataa$Cheese24_840_3 == '0'] <- ''
dataa$Cheese24_850_3[dataa$Cheese24_850_3 == '0'] <- ''
dataa$Cheese24_860_3[dataa$Cheese24_860_3 == '0'] <- ''
dataa$Cheese24_870_3[dataa$Cheese24_870_3 == '0'] <- ''
dataa$Cheese24_880_3[dataa$Cheese24_880_3 == '0'] <- ''
dataa$Cheese24_890_3[dataa$Cheese24_890_3 == '0'] <- ''
dataa$Cheese24_900_3[dataa$Cheese24_900_3 == '0'] <- ''
dataa$Cheese24_910_3[dataa$Cheese24_910_3 == '0'] <- ''
dataa$Cheese24_810_4[dataa$Cheese24_810_4 == '555'] <- '0.5'
dataa$Cheese24_810_4[dataa$Cheese24_810_4 == '200'] <- '0'
dataa$Cheese24_810_4[dataa$Cheese24_810_4 == '300'] <- '3'
dataa$Cheese24_810_4[dataa$Cheese24_810_4 == '0'] <- ''
dataa$Cheese24_820_4[dataa$Cheese24_820_4 == '555'] <- '0.5'
dataa$Cheese24_820_4[dataa$Cheese24_820_4 == '200'] <- '0'
dataa$Cheese24_820_4[dataa$Cheese24_820_4 == '300'] <- '3'
dataa$Cheese24_820_4[dataa$Cheese24_820_4 == '0'] <- ''
dataa$Cheese24_830_4[dataa$Cheese24_830_4 == '555'] <- '0.5'
dataa$Cheese24_830_4[dataa$Cheese24_830_4 == '200'] <- '0'
dataa$Cheese24_830_4[dataa$Cheese24_830_4 == '300'] <- '3'
dataa$Cheese24_830_4[dataa$Cheese24_830_4 == '0'] <- ''
dataa$Cheese24_840_4[dataa$Cheese24_840_4 == '555'] <- '0.5'
dataa$Cheese24_840_4[dataa$Cheese24_840_4 == '200'] <- '0'
dataa$Cheese24_840_4[dataa$Cheese24_840_4 == '300'] <- '3'
dataa$Cheese24_850_4[dataa$Cheese24_850_4 == '555'] <- '0.5'
dataa$Cheese24_850_4[dataa$Cheese24_850_4 == '200'] <- '0'
dataa$Cheese24_850_4[dataa$Cheese24_850_4 == '300'] <- '3'
dataa$Cheese24_860_4[dataa$Cheese24_860_4 == '555'] <- '0.5'
dataa$Cheese24_860_4[dataa$Cheese24_860_4 == '200'] <- '0'
dataa$Cheese24_860_4[dataa$Cheese24_860_4 == '300'] <- '3'
dataa$Cheese24_870_4[dataa$Cheese24_870_4 == '555'] <- '0.5'
dataa$Cheese24_870_4[dataa$Cheese24_870_4 == '200'] <- '0'
dataa$Cheese24_870_4[dataa$Cheese24_870_4 == '300'] <- '3'
dataa$Cheese24_880_4[dataa$Cheese24_880_4 == '555'] <- '0.5'
dataa$Cheese24_880_4[dataa$Cheese24_880_4 == '200'] <- '0'
dataa$Cheese24_880_4[dataa$Cheese24_880_4 == '300'] <- '3'
dataa$Cheese24_890_4[dataa$Cheese24_890_4 == '555'] <- '0.5'
dataa$Cheese24_890_4[dataa$Cheese24_890_4 == '200'] <- '0'
dataa$Cheese24_890_4[dataa$Cheese24_890_4 == '300'] <- '3'
dataa$Cheese24_900_4[dataa$Cheese24_900_4 == '555'] <- '0.5'
dataa$Cheese24_900_4[dataa$Cheese24_900_4 == '200'] <- '0'
dataa$Cheese24_900_4[dataa$Cheese24_900_4 == '300'] <- '3'
dataa$Cheese24_910_4[dataa$Cheese24_910_4 == '555'] <- '0.5'
dataa$Cheese24_910_4[dataa$Cheese24_910_4 == '200'] <- '0'
dataa$Cheese24_910_4[dataa$Cheese24_910_4 == '300'] <- '3'
dataa$Cheese24_840_4[dataa$Cheese24_840_4 == '0'] <- ''
dataa$Cheese24_850_4[dataa$Cheese24_850_4 == '0'] <- ''
dataa$Cheese24_860_4[dataa$Cheese24_860_4 == '0'] <- ''
dataa$Cheese24_870_4[dataa$Cheese24_870_4 == '0'] <- ''
dataa$Cheese24_880_4[dataa$Cheese24_880_4 == '0'] <- ''
dataa$Cheese24_890_4[dataa$Cheese24_890_4 == '0'] <- ''
dataa$Cheese24_900_4[dataa$Cheese24_900_4 == '0'] <- ''
dataa$Cheese24_910_4[dataa$Cheese24_910_4 == '0'] <- ''
write.csv(dataa, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data_all.csv",na='',row.names=FALSE)
rm(list = ls())
```


```{r}
#making cheese24 data workable
#add all kinds of cheese used
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_basline.csv')
dataa$all1 <- rowSums(dataa[,c("Cheese24_810Baseline","Cheese24_820Baseline","Cheese24_830Baseline","Cheese24_840Baseline","Cheese24_850Baseline","Cheese24_860Baseline","Cheese24_870Baseline","Cheese24_880Baseline","Cheese24_890Baseline","Cheese24_900Baseline","Cheese24_910Baseline")],na.rm=TRUE)
dataa$Cheese24sumBaseline<- ifelse(dataa$Cheese24Baseline=="NA",NA,dataa$all)
df2 <- dataa %>% select(-c(Cheese24Baseline,Cheese24_810Baseline,Cheese24_820Baseline,Cheese24_830Baseline,Cheese24_840Baseline,Cheese24_850Baseline,Cheese24_860Baseline,Cheese24_870Baseline,Cheese24_880Baseline,Cheese24_890Baseline,Cheese24_900Baseline,Cheese24_910Baseline,all1))
write.csv(df2, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data_cheese24_Baslinea.csv",na='',row.names=FALSE)
rm(list = ls())

dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_1.csv')
dataa$all1 <- rowSums(dataa[,c("Cheese24_810_1","Cheese24_820_1","Cheese24_830_1","Cheese24_840_1","Cheese24_850_1","Cheese24_860_1","Cheese24_870_1","Cheese24_880_1","Cheese24_890_1","Cheese24_900_1","Cheese24_910_1")],na.rm=TRUE)
dataa$Cheese24sum1<- ifelse(dataa$Cheese24_1=="NA",NA,dataa$all)
df2 <- dataa %>% select(-c(Cheese24_1,Cheese24_810_1,Cheese24_820_1,Cheese24_830_1,Cheese24_840_1,Cheese24_850_1,Cheese24_860_1,Cheese24_870_1,Cheese24_880_1,Cheese24_890_1,Cheese24_900_1,Cheese24_910_1,all1))
write.csv(df2, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data_cheese24_1a.csv",na='',row.names=FALSE)
rm(list = ls())

dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_2.csv')
dataa$all1 <- rowSums(dataa[,c("Cheese24_810_2","Cheese24_820_2","Cheese24_830_2","Cheese24_840_2","Cheese24_850_2","Cheese24_860_2","Cheese24_870_2","Cheese24_880_2","Cheese24_890_2","Cheese24_900_2","Cheese24_910_2")],na.rm=TRUE)
dataa$Cheese24sum2<- ifelse(dataa$Cheese24_2=="NA",NA,dataa$all)
df2 <- dataa %>% select(-c(Cheese24_2,Cheese24_810_2,Cheese24_820_2,Cheese24_830_2,Cheese24_840_2,Cheese24_850_2,Cheese24_860_2,Cheese24_870_2,Cheese24_880_2,Cheese24_890_2,Cheese24_900_2,Cheese24_910_2,all1))
write.csv(df2, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data_cheese24_2a.csv",na='',row.names=FALSE)
rm(list = ls())

dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_3.csv')
dataa$all1 <- rowSums(dataa[,c("Cheese24_810_3","Cheese24_820_3","Cheese24_830_3","Cheese24_840_3","Cheese24_850_3","Cheese24_860_3","Cheese24_870_3","Cheese24_880_3","Cheese24_890_3","Cheese24_900_3","Cheese24_910_3")],na.rm=TRUE)
dataa$Cheese24sum3<- ifelse(dataa$Cheese24_3=="NA",NA,dataa$all)
df2 <- dataa %>% select(-c(Cheese24_3,Cheese24_810_3,Cheese24_820_3,Cheese24_830_3,Cheese24_840_3,Cheese24_850_3,Cheese24_860_3,Cheese24_870_3,Cheese24_880_3,Cheese24_890_3,Cheese24_900_3,Cheese24_910_3,all1))
write.csv(df2, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data_cheese24_3a.csv",na='',row.names=FALSE)
rm(list = ls())

dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_4.csv')
dataa$all1 <- rowSums(dataa[,c("Cheese24_810_4","Cheese24_820_4","Cheese24_830_4","Cheese24_840_4","Cheese24_850_4","Cheese24_860_4","Cheese24_870_4","Cheese24_880_4","Cheese24_890_4","Cheese24_900_4","Cheese24_910_4")],na.rm=TRUE)
dataa$Cheese24sum4<- ifelse(dataa$Cheese24_4=="NA",NA,dataa$all)
df2 <- dataa %>% select(-c(Cheese24_4,Cheese24_810_4,Cheese24_820_4,Cheese24_830_4,Cheese24_840_4,Cheese24_850_4,Cheese24_860_4,Cheese24_870_4,Cheese24_880_4,Cheese24_890_4,Cheese24_900_4,Cheese24_910_4,all1))
write.csv(df2, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairy_data_cheese24_4a.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#get cheese data with everything else
dataa <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_all.csv')
datab <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_1a.csv')
datac<-merge(dataa,datab,by="EID")
rm(dataa)
rm(datab)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_2a.csv')
datab<-merge(dataa,datac,by="EID")
rm(dataa)
rm(datac)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_3a.csv')
datac<-merge(dataa,datab,by="EID")
rm(dataa)
rm(datab)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_4a.csv')
datab<-merge(dataa,datac,by="EID")
rm(dataa)
rm(datac)
dataa<-read.csv(file='C:/Users/timothy/Documents/GWAS_data/dairy/dairy_data_cheese24_Baslinea.csv')
datac<-merge(dataa,datab,by="EID")
rm(dataa)
rm(datab)

write.csv(datac, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_withCheese.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#add disease
dataa <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_withCheese.csv')
datab <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/UKBiobank_disease_Sept2017.csv')
datac<-merge(dataa,datab,by="EID")
rm(dataa)
rm(datab)
write.csv(datac, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_all_0317.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#check the disease
# central nervous system diseases (G00-G99), cerebrovascular diseases (I60-I69), or mental and behavioral disorders (F00-F99)

df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_all_0317.csv')


variables <- c("X41202.0.0", "X41202.0.1", "X41202.0.2", "X41202.0.3", "X41202.0.4", "X41202.0.5", "X41202.0.6", "X41202.0.7", "X41202.0.8")
df[variables] <- lapply(df[variables], as.character)

# Function to check if a value starts with any of the given prefixes
starts_with_any <- function(value, prefixes) {
  any(sapply(prefixes, function(prefix) startsWith(value, prefix)))
}

# Create 'dig' variable
df$dig <- apply(df[variables], 1, function(row) {
  has_G <- any(sapply(row, function(value) starts_with_any(value, c("G"))))
  has_F <- any(sapply(row, function(value) starts_with_any(value, c("F"))))
  has_I6 <- any(sapply(row, function(value) starts_with_any(value, c("I6"))))
  
  ifelse(has_G && has_F || has_G && has_I6 || has_F && has_I6, "M",
         ifelse(has_G, "G",
                ifelse(has_F, "F",
                       ifelse(has_I6, "I", NA))))
})
write.csv(df, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_all_0317_disease.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_all_0317_disease.csv')
# count the number of cases valid values (non-NA values) in both variables APOE_all and T40_Gcar
# Count cases with valid values in both variables
valid_cases <- sum(!is.na(df$APOE_all) & !is.na(df$T40_Gcar))
# Display the result
print(valid_cases)
```
```{r}
#sort data
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_all_0317_d_final.csv')

# Count occurrences of each value in 'dig' variable, including invalid values
value_counts <- table(addNA(df$dig))

# Display the result
print(value_counts)

#           F     G     I     M  <NA> 
# 12025    90   479    55    12     0 

# Exclude cases with 'dig' values "F", "G", "I", and "M"
filtered_df <- df[!df$dig %in% c("F", "G", "I", "M"), ]
write.csv(filtered_df, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_final0317.csv",na='',row.names=FALSE)
rm(list = ls())
```



```{r}
# in this part, the diet consumption is considered as the total captures.
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_final0317.csv')
# add all cheese 24 hour variable together
df <- df %>%
  mutate(
    Cheese24sum = if_else(
      rowSums(is.na(select(., Cheese24sumBaseline, Cheese24sum1, Cheese24sum2, Cheese24sum3, Cheese24sum4))) == 5,
      NA_real_,
      coalesce(Cheese24sumBaseline, 0) +
        coalesce(Cheese24sum1, 0) +
        coalesce(Cheese24sum2, 0) +
        coalesce(Cheese24sum3, 0) +
        coalesce(Cheese24sum4, 0)
    )
  )
# add all milk intake variable together
df <- df %>%
  mutate(
    Milksum = if_else(
      rowSums(is.na(select(., MilkIntakeBaseline, MilkIntake1, MilkIntake2, MilkIntake3, MilkIntake4))) == 5,
      NA_real_,
      coalesce(MilkIntakeBaseline, 0) +
        coalesce(MilkIntake1, 0) +
        coalesce(MilkIntake2, 0) +
        coalesce(MilkIntake3, 0) +
        coalesce(MilkIntake4, 0)
    )
  )
# add all Fmilk intake variables together
df <- df %>%
  mutate(
    FMilksum = if_else(
      rowSums(is.na(select(., FMilkIntakeBaseline, FMilkIntake1, FMilkIntake2, FMilkIntake3, FMilkIntake4))) == 5,
      NA_real_,
      coalesce(FMilkIntakeBaseline, 0) +
        coalesce(FMilkIntake1, 0) +
        coalesce(FMilkIntake2, 0) +
        coalesce(FMilkIntake3, 0) +
        coalesce(FMilkIntake4, 0)
    )
  )

# add all red wine 24 hours together
df <- df %>%
  mutate(
    Redwine24sum = if_else(
      rowSums(is.na(select(., RedwineBase24, Redwine24_1, Redwine24_2, Redwine24_3, Redwine24_4))) == 5,
      NA_real_,
      coalesce(RedwineBase24, 0) +
        coalesce(Redwine24_1, 0) +
        coalesce(Redwine24_2, 0) +
        coalesce(Redwine24_3, 0) +
        coalesce(Redwine24_4, 0)
    )
  )
#in this version, the diet total consumption (red wine, cheese, milk, fmilk) variable is added
write.csv(df, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_final0319.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
# create mean value for each variables
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_final0319.csv')
# make cheese mean
df <- df %>%
  mutate(
    Cheese24mean = if_else(
      rowSums(is.na(select(., Cheese24sumBaseline, Cheese24sum1, Cheese24sum2, Cheese24sum3, Cheese24sum4))) == 5,
      NA_real_,
      rowMeans(select(., Cheese24sumBaseline, Cheese24sum1, Cheese24sum2, Cheese24sum3, Cheese24sum4), na.rm = TRUE)
    )
  )
# make milk mean
df <- df %>%
  mutate(
    milkmean = if_else(
      rowSums(is.na(select(., MilkIntakeBaseline, MilkIntake1, MilkIntake2, MilkIntake3, MilkIntake4))) == 5,
      NA_real_,
      rowMeans(select(., MilkIntakeBaseline, MilkIntake1, MilkIntake2, MilkIntake3, MilkIntake4), na.rm = TRUE)
    )
  )
# make Fmilk mean
df <- df %>%
  mutate(
    Fmilkmean = if_else(
      rowSums(is.na(select(., FMilkIntakeBaseline, FMilkIntake1, FMilkIntake2, FMilkIntake3, FMilkIntake4))) == 5,
      NA_real_,
      rowMeans(select(., FMilkIntakeBaseline, FMilkIntake1, FMilkIntake2, FMilkIntake3, FMilkIntake4), na.rm = TRUE)
    )
  )
# make red wine mean
df <- df %>%
  mutate(
    Redwine24mean = if_else(
      rowSums(is.na(select(., RedwineBase24, Redwine24_1, Redwine24_2, Redwine24_3, Redwine24_4))) == 5,
      NA_real_,
      rowMeans(select(., RedwineBase24, Redwine24_1, Redwine24_2, Redwine24_3, Redwine24_4), na.rm = TRUE)
    )
  )
# the 0320 version includes mean values
write.csv(df, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_final0320.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#check cases numbers for valid values for both family history, APOE4, and TOMM40
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_final0320.csv')
valid_cases <- complete.cases(df$family_history_AD, df$T40_Gcar, df$APOE_all)
num_valid_cases <- sum(valid_cases)
rm(list = ls())
```

```{r}
#check cases numbers for valid values for all fixed predictors or explanatory variables
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_final0320.csv')
df1 <- df[complete.cases(df$family_history_AD, df$T40_Gcar, df$APOE_all, df$Sex, df$Age_Baseline, df$Townsend, df$SmokingY08, df$AlcoholY08, df$BMI_Y08andY12andY14_mean), ]
write.csv(df1, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_0527_valid.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#select red wine data
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_0527_valid.csv')
df1 <- df[complete.cases(df$family_history_AD, df$T40_Gcar, df$APOE_all, df$Sex, df$Age_Baseline, df$Townsend, df$SmokingY08, df$AlcoholY08, df$BMI_Y08andY12andY14_mean, df$Redwine24mean), ]
write.csv(df1, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_redwine.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#select milk data
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_0527_valid.csv')
df1 <- df[complete.cases(df$family_history_AD, df$T40_Gcar, df$APOE_all, df$Sex, df$Age_Baseline, df$Townsend, df$SmokingY08, df$AlcoholY08, df$BMI_Y08andY12andY14_mean, df$milkmean), ]
write.csv(df1, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_milk.csv",na='',row.names=FALSE)
rm(list = ls())
```

```{r}
#select cheese data
df <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/dairydata_0527_valid.csv')
df1 <- df[complete.cases(df$family_history_AD, df$T40_Gcar, df$APOE_all, df$Sex, df$Age_Baseline, df$Townsend, df$SmokingY08, df$AlcoholY08, df$BMI_Y08andY12andY14_mean, df$Cheese24mean), ]
write.csv(df1, "C:\\Users\\timothy\\Documents\\GWAS_data\\dairy\\dairydata_cheese.csv",na='',row.names=FALSE)
rm(list = ls())
```